namespace OpenCode.Schema;

using System.Text.Json.Serialization;

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    WriteIndented = false
)]
[JsonSerializable(typeof(SessionId))]
[JsonSerializable(typeof(ProjectId))]
[JsonSerializable(typeof(MessageId))]
[JsonSerializable(typeof(ModelId))]
[JsonSerializable(typeof(VariantId))]
[JsonSerializable(typeof(ProviderId))]
[JsonSerializable(typeof(CredentialId))]
[JsonSerializable(typeof(PermissionId))]
[JsonSerializable(typeof(EventId))]
[JsonSerializable(typeof(WorkspaceId))]
[JsonSerializable(typeof(ShellId))]
[JsonSerializable(typeof(PtyId))]
[JsonSerializable(typeof(SnapshotId))]
[JsonSerializable(typeof(SkillId))]
[JsonSerializable(typeof(FormId))]
[JsonSerializable(typeof(IntegrationId))]
[JsonSerializable(typeof(PermissionSavedId))]
[JsonSerializable(typeof(PluginId))]
[JsonSerializable(typeof(Money))]
[JsonSerializable(typeof(TokenUsageInfo))]
[JsonSerializable(typeof(ModelRef))]
[JsonSerializable(typeof(ModelInfo))]
[JsonSerializable(typeof(ProviderInfo))]
[JsonSerializable(typeof(SessionInfo))]
[JsonSerializable(typeof(SessionForkInfo))]
[JsonSerializable(typeof(ForkBoundary))]
[JsonSerializable(typeof(ForkBoundaryBefore))]
[JsonSerializable(typeof(ForkBoundaryThrough))]
[JsonSerializable(typeof(SessionRevert))]
[JsonSerializable(typeof(SessionStructuredError))]
[JsonSerializable(typeof(SessionStatsInfo))]
[JsonSerializable(typeof(SessionTransferData))]
[JsonSerializable(typeof(PromptInput))]
[JsonSerializable(typeof(SessionMessage))]
[JsonSerializable(typeof(UserMessage))]
[JsonSerializable(typeof(AssistantMessage))]
[JsonSerializable(typeof(AgentInfo))]
[JsonSerializable(typeof(PermissionRequest))]
[JsonSerializable(typeof(PermissionSavedInfo))]
[JsonSerializable(typeof(ProjectInfo))]
[JsonSerializable(typeof(CredentialInfo))]
[JsonSerializable(typeof(SessionInboxItem))]
[JsonSerializable(typeof(LocationRef))]
[JsonSerializable(typeof(LocationInfo))]
[JsonSerializable(typeof(WorkspaceDestroyResult))]
[JsonSerializable(typeof(WorktreeInfo))]
[JsonSerializable(typeof(VcsInfo))]
[JsonSerializable(typeof(VcsFileStatus))]
[JsonSerializable(typeof(FileDiffInfo))]
[JsonSerializable(typeof(ShellInfo))]
[JsonSerializable(typeof(PtyInfo))]
[JsonSerializable(typeof(SkillInfo))]
[JsonSerializable(typeof(CommandInfo))]
[JsonSerializable(typeof(QuestionPrompt))]
[JsonSerializable(typeof(McpServerConfig))]
[JsonSerializable(typeof(McpLocalConfig))]
[JsonSerializable(typeof(McpRemoteConfig))]
[JsonSerializable(typeof(FileSystemEntry))]
[JsonSerializable(typeof(FileSystemMatch))]
[JsonSerializable(typeof(FileSystemFindInput))]
[JsonSerializable(typeof(InstructionEntryInfo))]
[JsonSerializable(typeof(InstructionEntrySnapshot))]
[JsonSerializable(typeof(ReferenceInfo))]
[JsonSerializable(typeof(ConnectionInfo))]
[JsonSerializable(typeof(ConnectionCredentialInfo))]
[JsonSerializable(typeof(ConnectionEnvInfo))]
[JsonSerializable(typeof(IntegrationInfo))]
[JsonSerializable(typeof(OpenCodeConfiguration))]
[JsonSerializable(typeof(OpenCodeEvent))]
[JsonSerializable(typeof(PtyConnectToken))]
[JsonSerializable(typeof(PersistentPtyInfo))]
[JsonSerializable(typeof(PersistentPtyHandoff))]
[JsonSerializable(typeof(PluginInfo))]
[JsonSerializable(typeof(WebSearchResponse))]
[JsonSerializable(typeof(OpenCodeConfig))]
[JsonSerializable(typeof(Dictionary<string, AuthEntry>))]
public partial class OpenCodeJsonContext : JsonSerializerContext
{
}
