<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup><ProjectReference Include="..\Transport.Pipelines\Transport.Pipelines.csproj" /></ItemGroup>

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Update="runtimes\**" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" Pack="true" PackagePath="%(Identity)" />
    <None Update="LICENSE.opentui" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
