// Generated from packages/tui/src/config/keybind.ts, TuiKeybind.Definitions.
// Regenerate with GenerateDefaults.ps1 -Source <TypeScript keybind.ts>.
namespace OpenCode.Cli.Tui.Keymap;

public sealed record DefaultBinding(string Id, string Key, string Description, bool PreventDefault);

public static class DefaultBindings
{
    public static IReadOnlyList<DefaultBinding> All { get; } = Array.AsReadOnly<DefaultBinding>([
        new("leader", "ctrl+x", "Leader key for keybind combinations", true),
        new("app.exit", "ctrl+c,ctrl+d,<leader>q", "Exit the application", true),
        new("app.debug", "none", "Toggle debug panel", true),
        new("app.console", "none", "Toggle console", true),
        new("app.scrap", "none", "Open scrap screen", true),
        new("app.toggle.animations", "none", "Toggle animations", true),
        new("app.toggle.file_context", "none", "Toggle file context", true),
        new("app.toggle.diffwrap", "none", "Toggle diff wrapping", true),
        new("app.toggle.paste_summary", "none", "Toggle paste summary", true),
        new("command.palette.show", "ctrl+p", "List available commands", true),
        new("help.show", "none", "Open help dialog", true),
        new("docs.open", "none", "Open documentation", true),
        new("opencode.settings", "none", "Open settings", true),
        new("server.pair", "none", "Pair device", true),
        new("service.restart", "none", "Restart service", true),
        new("permission.mode", "none", "Toggle auto-approve permissions", true),
        new("diff.open", "none", "Open diff viewer", true),
        new("diff.close", "escape,q", "Close diff viewer", true),
        new("diff.down", "j,down", "Move diff viewer down", true),
        new("diff.up", "k,up", "Move diff viewer up", true),
        new("diff.page.down", "pagedown,ctrl+f", "Page diff viewer down", true),
        new("diff.page.up", "pageup,ctrl+b", "Page diff viewer up", true),
        new("diff.half_page.down", "ctrl+d", "Scroll diff viewer down half a page", true),
        new("diff.half_page.up", "ctrl+u", "Scroll diff viewer up half a page", true),
        new("diff.first", "gg,home", "Go to the start of the diff", true),
        new("diff.last", "shift+g,end", "Go to the end of the diff", true),
        new("diff.toggle", "none", "Deprecated: file tree is mouse-controlled", true),
        new("diff.expand", "none", "Deprecated: file tree is mouse-controlled", true),
        new("diff.expand_all", "none", "Deprecated: file tree is mouse-controlled", true),
        new("diff.collapse", "none", "Deprecated: file tree is mouse-controlled", true),
        new("diff.switch_focus", "none", "Deprecated: keyboard navigation always controls the diff", true),
        new("diff.next_hunk", "]", "Jump to next diff hunk", true),
        new("diff.previous_hunk", "[", "Jump to previous diff hunk", true),
        new("diff.next_file", "n,alt+down", "Jump to next diff file", true),
        new("diff.previous_file", "p,alt+up", "Jump to previous diff file", true),
        new("diff.toggle_file_tree", "b", "Toggle diff viewer file tree", true),
        new("diff.single_patch", "s", "Toggle single patch view", true),
        new("diff.switch_source", "d", "Switch diff viewer source", true),
        new("diff.toggle_view", "v", "Toggle diff viewer split or unified view", true),
        new("diff.mark_reviewed", "m", "Toggle selected diff file reviewed", true),
        new("diff.help", "?,shift+?,shift+/", "Show more diff viewer shortcuts", true),
        new("prompt.editor", "<leader>e", "Open external editor", true),
        new("theme.switch", "<leader>t", "List available themes", true),
        new("theme.switch_mode", "none", "Switch between light and dark theme mode", true),
        new("theme.mode.lock", "none", "Lock or unlock theme mode", true),
        new("session.sidebar.toggle", "<leader>b", "Toggle sidebar", true),
        new("pane.focus.left", "<leader>left", "Focus session pane", true),
        new("pane.focus.right", "<leader>right", "Focus terminal pane", true),
        new("terminal.select", "<leader>down", "Select terminal", true),
        new("terminal.toggle", "none", "Toggle terminal pane", true),
        new("terminal.close", "<leader>up", "Close terminal pane", true),
        new("session.toggle.scrollbar", "none", "Toggle session scrollbar", true),
        new("opencode.status", "<leader>s", "View status", true),
        new("opencode.debug", "none", "View debug info", true),
        new("session.export", "<leader>x", "Export session to editor", true),
        new("session.copy", "none", "Copy session transcript", true),
        new("session.move", "none", "Move session", true),
        new("session.new", "<leader>n", "Create a new session", true),
        new("session.list", "<leader>l", "List all sessions", true),
        new("open.menu", "ctrl+o", "Open recent sessions and projects", true),
        new("session.tab.next", "ctrl+tab,alt+down", "Switch to next open session tab", true),
        new("session.tab.previous", "ctrl+shift+tab,alt+up", "Switch to previous open session tab", true),
        new("session.tab.history.back", "none", "Go back in session tab history", true),
        new("session.tab.history.forward", "ctrl+i", "Go forward in session tab history", true),
        new("session.tab.next_unread", "alt+shift+down", "Switch to next unread session tab", true),
        new("session.tab.previous_unread", "alt+shift+up", "Switch to previous unread session tab", true),
        new("session.tab.close", "<leader>w", "Close current session tab", true),
        new("session.tab.reopen", "ctrl+shift+t", "Reopen last closed session tab", true),
        new("session.timeline", "<leader>g", "Show session timeline", true),
        new("session.fork", "none", "Fork session from message", true),
        new("session.rename", "ctrl+r", "Rename session", true),
        new("session.delete", "ctrl+d", "Delete session", true),
        new("session.share", "none", "Share current session", true),
        new("session.unshare", "none", "Unshare current session", true),
        new("session.interrupt", "escape", "Interrupt current session", true),
        new("session.background", "ctrl+b", "Background blocking session tools", true),
        new("session.compact", "<leader>c", "Compact the session", true),
        new("session.cd", "none", "Change working directory", true),
        new("session.queued_prompts", "<leader>q", "Manage queued prompts", true),
        new("queued_prompt.delete", "ctrl+d", "Delete queued prompt", true),
        new("session.toggle.exploration_grouping", "none", "Toggle related tool call grouping", true),
        new("session.child.first", "down", "Toggle subagent picker", true),
        new("session.child.next", "right", "Go to next child session", true),
        new("session.child.previous", "left", "Go to previous child session", true),
        new("session.parent", "up", "Go to parent session", true),
        new("session.pin.toggle", "ctrl+f", "Pin or unpin session in the session list", true),
        new("session.quick_switch.1", "<leader>1", "Switch to session in quick slot 1", true),
        new("session.quick_switch.2", "<leader>2", "Switch to session in quick slot 2", true),
        new("session.quick_switch.3", "<leader>3", "Switch to session in quick slot 3", true),
        new("session.quick_switch.4", "<leader>4", "Switch to session in quick slot 4", true),
        new("session.quick_switch.5", "<leader>5", "Switch to session in quick slot 5", true),
        new("session.quick_switch.6", "<leader>6", "Switch to session in quick slot 6", true),
        new("session.quick_switch.7", "<leader>7", "Switch to session in quick slot 7", true),
        new("session.quick_switch.8", "<leader>8", "Switch to session in quick slot 8", true),
        new("session.quick_switch.9", "<leader>9", "Switch to session in quick slot 9", true),
        new("session.tab.select.1", "<leader>1,ctrl+1", "Switch to session tab 1", true),
        new("session.tab.select.2", "<leader>2,ctrl+2", "Switch to session tab 2", true),
        new("session.tab.select.3", "<leader>3,ctrl+3", "Switch to session tab 3", true),
        new("session.tab.select.4", "<leader>4,ctrl+4", "Switch to session tab 4", true),
        new("session.tab.select.5", "<leader>5,ctrl+5", "Switch to session tab 5", true),
        new("session.tab.select.6", "<leader>6,ctrl+6", "Switch to session tab 6", true),
        new("session.tab.select.7", "<leader>7,ctrl+7", "Switch to session tab 7", true),
        new("session.tab.select.8", "<leader>8,ctrl+8", "Switch to session tab 8", true),
        new("session.tab.select.9", "<leader>9,ctrl+9", "Switch to session tab 9", true),
        new("session.tab.select.10", "<leader>0,ctrl+0", "Switch to session tab 10", true),
        new("stash.delete", "ctrl+d", "Delete stash entry", true),
        new("model.dialog.provider", "ctrl+a", "Open provider list from model dialog", true),
        new("model.dialog.favorite", "ctrl+f", "Toggle model favorite status", true),
        new("model.list", "<leader>m", "List available models", true),
        new("model.cycle_recent", "f2", "Next recently used model", true),
        new("model.cycle_recent_reverse", "shift+f2", "Previous recently used model", true),
        new("model.cycle_favorite", "none", "Next favorite model", true),
        new("model.cycle_favorite_reverse", "none", "Previous favorite model", true),
        new("mcp.list", "none", "List MCP servers", true),
        new("provider.connect", "none", "Connect integration", true),
        new("agent.list", "<leader>a", "List agents", true),
        new("agent.cycle", "shift+tab", "Next agent", true),
        new("agent.cycle.reverse", "none", "Previous agent", true),
        new("variant.cycle", "ctrl+t", "Cycle model variants", true),
        new("variant.list", "none", "List model variants", true),
        new("session.page.up", "pageup,ctrl+alt+b", "Scroll messages up by one page", true),
        new("session.page.down", "pagedown,ctrl+alt+f", "Scroll messages down by one page", true),
        new("session.line.up", "ctrl+alt+y", "Scroll messages up by one line", true),
        new("session.line.down", "ctrl+alt+e", "Scroll messages down by one line", true),
        new("session.half.page.up", "ctrl+alt+u", "Scroll messages up by half page", true),
        new("session.half.page.down", "ctrl+alt+d", "Scroll messages down by half page", true),
        new("session.first", "ctrl+g,home,alt+home", "Navigate to first message", true),
        new("session.last", "ctrl+alt+g,end", "Navigate to last message", true),
        new("session.message.next", "none", "Navigate to next message", true),
        new("session.message.previous", "none", "Navigate to previous message", true),
        new("session.message.user.next", "none", "Navigate to next user message", true),
        new("session.message.user.previous", "none", "Navigate to previous user message", true),
        new("session.messages_last_user", "alt+end", "Navigate to last user message", true),
        new("messages.copy", "<leader>y", "Copy message", true),
        new("session.undo", "<leader>u", "Undo message", true),
        new("session.redo", "<leader>r", "Redo message", true),
        new("session.toggle.thinking", "none", "Toggle thinking blocks visibility", true),
        new("prompt.submit", "none", "Submit prompt", true),
        new("prompt.queue", "<leader>return", "Queue prompt", true),
        new("prompt.editor_context.clear", "none", "Clear editor context", true),
        new("prompt.images.view", "<leader>i", "View image attachments", true),
        new("prompt.skills", "none", "Open skill selector", true),
        new("prompt.stash", "none", "Stash prompt", true),
        new("prompt.stash.pop", "none", "Pop stashed prompt", true),
        new("prompt.stash.list", "none", "List stashed prompts", true),
        new("prompt.clear", "ctrl+c", "Clear input field", true),
        new("prompt.paste", "ctrl+v", "Paste from clipboard", false),
        new("input.submit", "return", "Submit input", true),
        new("input.newline", "shift+return,ctrl+return,alt+return,ctrl+j", "Insert newline in input", true),
        new("input.move.left", "left,ctrl+b", "Move cursor left in input", true),
        new("input.move.right", "right,ctrl+f", "Move cursor right in input", true),
        new("input.move.up", "up", "Move cursor up in input", true),
        new("input.move.down", "down", "Move cursor down in input", true),
        new("input.select.left", "shift+left", "Select left in input", true),
        new("input.select.right", "shift+right", "Select right in input", true),
        new("input.select.up", "shift+up", "Select up in input", true),
        new("input.select.down", "shift+down", "Select down in input", true),
        new("input.line.home", "ctrl+a", "Move to start of line in input", true),
        new("input.line.end", "ctrl+e", "Move to end of line in input", true),
        new("input.select.line.home", "ctrl+shift+a", "Select to start of line in input", true),
        new("input.select.line.end", "ctrl+shift+e", "Select to end of line in input", true),
        new("input.visual.line.home", "alt+a", "Move to start of visual line in input", true),
        new("input.visual.line.end", "alt+e", "Move to end of visual line in input", true),
        new("input.select.visual.line.home", "alt+shift+a", "Select to start of visual line in input", true),
        new("input.select.visual.line.end", "alt+shift+e", "Select to end of visual line in input", true),
        new("input.buffer.home", "none", "Move to start of buffer in input", true),
        new("input.buffer.end", "none", "Move to end of buffer in input", true),
        new("input.select.buffer.home", "shift+home", "Select to start of buffer in input", true),
        new("input.select.buffer.end", "shift+end", "Select to end of buffer in input", true),
        new("input.delete.line", "ctrl+shift+d", "Delete line in input", true),
        new("input.delete.to.line.end", "ctrl+k", "Delete to end of line in input", true),
        new("input.delete.to.line.start", "ctrl+u", "Delete to start of line in input", true),
        new("input.backspace", "backspace,shift+backspace", "Backspace in input", true),
        new("input.delete", "ctrl+d,delete,shift+delete", "Delete character in input", true),
        new("input.undo", "ctrl+-,super+z", "Undo in input", true),
        new("input.redo", "ctrl+.,super+shift+z", "Redo in input", true),
        new("input.word.forward", "alt+f,alt+right,ctrl+right", "Move word forward in input", true),
        new("input.word.backward", "alt+b,alt+left,ctrl+left", "Move word backward in input", true),
        new("input.select.word.forward", "alt+shift+f,alt+shift+right", "Select word forward in input", true),
        new("input.select.word.backward", "alt+shift+b,alt+shift+left", "Select word backward in input", true),
        new("input.delete.word.forward", "alt+d,alt+delete,ctrl+delete", "Delete word forward in input", true),
        new("input.delete.word.backward", "ctrl+w,ctrl+backspace,alt+backspace", "Delete word backward in input", true),
        new("input.select.all", "super+a", "Select all in input", true),
        new("prompt.history.previous", "up", "Previous history item", true),
        new("prompt.history.next", "down", "Next history item", true),
        new("composer.subagent.up", "up", "Previous subagent", true),
        new("composer.subagent.down", "down", "Next subagent", true),
        new("composer.subagent.select", "return", "Navigate to subagent", true),
        new("composer.subagent.interrupt", "ctrl+d", "Interrupt subagent", true),
        new("composer.shell.up", "up", "Previous shell", true),
        new("composer.shell.down", "down", "Next shell", true),
        new("composer.shell.kill", "ctrl+d", "Kill shell command", true),
        new("composer.terminal.up", "up,k", "Previous terminal", true),
        new("composer.terminal.down", "down,j", "Next terminal", true),
        new("composer.terminal.select", "return", "Select terminal", true),
        new("dialog.select.prev", "up,ctrl+p", "Move to previous dialog item", true),
        new("dialog.select.next", "down,ctrl+n", "Move to next dialog item", true),
        new("dialog.select.page_up", "pageup", "Move up one page in dialog", true),
        new("dialog.select.page_down", "pagedown", "Move down one page in dialog", true),
        new("dialog.select.home", "home", "Move to first dialog item", true),
        new("dialog.select.end", "end", "Move to last dialog item", true),
        new("dialog.select.submit", "return", "Submit selected dialog item", true),
        new("dialog.prompt.submit", "return", "Submit dialog prompt", true),
        new("dialog.integration.rename", "ctrl+r", "Rename integration account", true),
        new("dialog.integration.delete", "ctrl+d", "Delete integration account", true),
        new("dialog.worktree.generate", "tab", "Generate worktree name", true),
        new("dialog.move_session.new", "ctrl+m", "New worktree", true),
        new("dialog.move_session.delete", "ctrl+d", "Delete worktree", true),
        new("dialog.move_session.refresh", "ctrl+r", "Refresh worktrees", true),
        new("prompt.autocomplete.prev", "up,ctrl+p", "Move to previous autocomplete item", true),
        new("prompt.autocomplete.next", "down,ctrl+n", "Move to next autocomplete item", true),
        new("prompt.autocomplete.hide", "escape", "Hide autocomplete", true),
        new("prompt.autocomplete.select", "return", "Select autocomplete item", true),
        new("prompt.autocomplete.complete", "tab", "Complete autocomplete item", true),
        new("permission.prompt.fullscreen", "ctrl+f", "Toggle permission prompt fullscreen", true),
        new("plugins.toggle", "space", "Toggle plugin", true),
        new("dialog.mcp.toggle", "space", "Toggle MCP server", true),
        new("dialog.plugins.install", "shift+i", "Install plugin from plugin dialog", true),
        new("terminal.suspend", "ctrl+z", "Suspend terminal", true),
        new("terminal.title.toggle", "none", "Toggle terminal title", true),
        new("plugins.list", "none", "Open plugin manager dialog", true),
        new("plugins.install", "none", "Install plugin", true),
        new("which-key.toggle", "ctrl+alt+k", "Toggle which-key panel", true),
        new("which-key.layout.toggle", "ctrl+alt+shift+k", "Switch which-key layout", true),
        new("which-key.pending.toggle", "ctrl+alt+shift+p", "Toggle which-key pending preview", true),
        new("which-key.group.previous", "ctrl+alt+left,ctrl+alt+[", "Previous which-key group", true),
        new("which-key.group.next", "ctrl+alt+right,ctrl+alt+]", "Next which-key group", true),
        new("which-key.scroll.up", "ctrl+alt+up,ctrl+alt+p", "Scroll which-key up", true),
        new("which-key.scroll.down", "ctrl+alt+down,ctrl+alt+n", "Scroll which-key down", true),
        new("which-key.page.up", "ctrl+alt+pageup", "Page which-key up", true),
        new("which-key.page.down", "ctrl+alt+pagedown", "Page which-key down", true),
        new("which-key.home", "ctrl+alt+home", "Jump to first which-key binding", true),
        new("which-key.end", "ctrl+alt+end", "Jump to last which-key binding", true),
    ]);
}
