param([Parameter(Mandatory = $true)][string] $UpstreamRoot)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
$root = (Resolve-Path -LiteralPath $UpstreamRoot).Path
$commit = & git -C $root rev-parse HEAD
if ($LASTEXITCODE -ne 0 -or $commit -notmatch '^[0-9a-f]{40}$') { throw 'Cannot determine upstream commit.' }
$schemaPath = Join-Path $root 'packages/core/src/database/schema.gen.ts'
$registryPath = Join-Path $root 'packages/core/src/database/migration.gen.ts'
$schema = [IO.File]::ReadAllText($schemaPath)
$registry = [IO.File]::ReadAllText($registryPath)

# Decode only the literal tx.run statements emitted by core/script/migration.ts.
# Reject new executable syntax rather than silently generating an incomplete schema.
$calls = [regex]::new('yield\*\s+tx\.run\(\s*`((?:\\.|[^`\\])*)`\s*,?\s*\)', 'Singleline')
$matches = $calls.Matches($schema)
$remaining = $calls.Replace($schema, '') -replace '\s', ''
$wrapper = 'import{Effect}from"effect"importtype{DatabaseMigration}from"./migration.js"constschema:Omit<DatabaseMigration.Migration,"id">={up(tx){returnEffect.gen(function*(){})},}exportdefaultschema'
if ($remaining -cne $wrapper -or $matches.Count -eq 0) { throw 'Unsupported schema generator output. Review the upstream generator before updating this extractor.' }
$statements = @($matches | ForEach-Object {
    $literal = $_.Groups[1].Value
    if ($literal.Contains('${') -or ($literal.Replace('\`', '').Contains('\'))) { throw 'Unsupported SQL template escape or interpolation.' }
    $sql = $literal.Replace('\`', '`').Trim() -replace "`r`n", "`n"
    $sql = $sql -replace '(?m)^ {8}', ''
    if ($sql.Contains('"""')) { throw 'Unsupported C# raw string delimiter in SQL.' }
    $sql
})

$imports = @{}
foreach ($match in [regex]::Matches($registry, 'import (m\d+) from "\./migration/([^"]+)\.js"')) {
    $name = $match.Groups[2].Value
    $migration = [IO.File]::ReadAllText((Join-Path $root "packages/core/src/database/migration/$name.ts"))
    $ids = [regex]::Matches($migration, '(?m)^\s+id: "([^"]+)"')
    if ($ids.Count -ne 1 -or $ids[0].Groups[1].Value -cne $name) { throw "Migration ID does not match its registry entry: $name" }
    $imports.Add($match.Groups[1].Value, $name)
}
$list = [regex]::Match($registry, 'export const migrations = \[([^\]]+)\] satisfies DatabaseMigration\.Migration\[\]', 'Singleline')
if (!$list.Success -or ($list.Groups[1].Value -replace 'm\d+|,|\s', '') -ne '') { throw 'Unsupported migration registry.' }
$migrationIds = @([regex]::Matches($list.Groups[1].Value, 'm\d+') | ForEach-Object { $imports[$_.Value] })
if ($migrationIds.Count -ne $imports.Count -or @($migrationIds | Sort-Object -Unique).Count -ne $imports.Count) { throw 'Incomplete or duplicate migration registry.' }

$tables = @()
$indexes = @()
foreach ($sql in $statements) {
    if ($sql -match '^CREATE TABLE `([^`]+)`') { $tables += $Matches[1]; continue }
    if ($sql -match '^CREATE (?:UNIQUE )?INDEX `([^`]+)`') { $indexes += $Matches[1]; continue }
    throw 'The schema snapshot contains a statement other than canonical table/index creation.'
}

$lines = [Collections.Generic.List[string]]::new()
$lines.Add('// <auto-generated> Generated by GenerateBootstrap.ps1; do not edit. </auto-generated>')
$lines.Add("// Upstream: https://github.com/sst/opencode; commit $commit")
$lines.Add('// Worktree inputs are identified by SHA-256 below, including any uncommitted source changes.')
foreach ($relative in @('packages/core/src/database/schema.gen.ts', 'packages/core/src/database/migration.gen.ts', 'packages/core/src/database/migration.ts', 'packages/core/script/migration.ts')) {
    $hash = (Get-FileHash -LiteralPath (Join-Path $root $relative) -Algorithm SHA256).Hash.ToLowerInvariant()
    $lines.Add("// $relative SHA-256 $hash")
}
foreach ($line in ([IO.File]::ReadAllText((Join-Path $root 'LICENSE')) -split '\r?\n')) { $lines.Add(('// ' + $line).TrimEnd()) }
$lines.Add('namespace OpenCode.Core.Database;')
$lines.Add('')
$lines.Add('internal static class DatabaseBootstrapSchema')
$lines.Add('{')
$lines.Add('    internal static readonly string[] Statements =')
$lines.Add('    [')
foreach ($sql in $statements) {
    $lines.Add('        """')
    foreach ($line in ($sql -split "`n")) { $lines.Add('        ' + $line) }
    $lines.Add('        """,')
}
$lines.Add('    ];')
foreach ($entry in @(@('MigrationIds', $migrationIds), @('Tables', $tables), @('Indexes', $indexes))) {
    $lines.Add('')
    $lines.Add('    internal static readonly string[] ' + $entry[0] + ' =')
    $lines.Add('    [')
    foreach ($name in $entry[1]) { $lines.Add('        "' + $name + '",') }
    $lines.Add('    ];')
}
$lines.Add('}')
[IO.File]::WriteAllText((Join-Path $PSScriptRoot 'DatabaseBootstrapSchema.Generated.cs'), ($lines -join "`n") + "`n", [Text.UTF8Encoding]::new($false))
Write-Output "Generated $($tables.Count) tables, $($indexes.Count) indexes, and $($migrationIds.Count) baseline migration IDs. No SQL was executed."
